# Generated by Django 3.0.2 on 2020-04-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeimerModelConstants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True, unique=True)),
                ('plasma_speed', models.FloatField()),
                ('plasma_density', models.FloatField()),
                ('magnetic_by', models.FloatField()),
                ('magnetic_bz', models.FloatField()),
            ],
        ),
    ]
