# Generated by Django 3.0.2 on 2020-05-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='weimermodelconstants',
            index=models.Index(fields=['datetime'], name='main_weimer_datetim_1d9fed_idx'),
        ),
    ]
